### ISSUE TITLE
Demo code not working--NotFoundError:

### ISSUE THREAD

**Issue by DreamRT** [Sekunde/3D-SIS#11]
Greetings!

Your example.sh doesn't seem to be working. Some issues I've found:

Called with args:
Namespace(cfg='ScanNet/example', debug=False, epochs=100000, gpu='0', mode='benchmark', num_workers=1, output_dir='example_result/scannet_benchmark_checkpoint', step='1205541', tag=None)
... ...

Traceback (most recent call last):
  File "main.py", line 84, in <module>
    benchmark(args)
  File "F:\3D SIS\code\lib\model\trainval.py", line 64, in benchmark
    logger = Logger(os.path.join(log_dir, 'test'))
  File "F:\3D SIS\code\lib\utils\logger.py", line 15, in __init__
    self.writer = tf.summary.FileWriter(log_dir)
  File "D:\Anaconda3\Anaconda3c\envs\python368\lib\site-packages\tensorflow\python\summary\writer\writer.py", line 336, in __init__
    filename_suffix)
  File "D:\Anaconda3\Anaconda3c\envs\python368\lib\site-packages\tensorflow\python\summary\writer\event_file_writer.py", line 67, in __init__
    gfile.MakeDirs(self._logdir)
  File "D:\Anaconda3\Anaconda3c\envs\python368\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 368, in recursive_create_dir
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)
  File "D:\Anaconda3\Anaconda3c\envs\python368\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: example_result/scannet_benchmark_checkpoint\ScanNet/example\logs\test; No such file or directory

**Comment by Sekunde** [comment]
it seems something wrong in creating folder, are you using a linux system there?

**Comment by DreamRT** [comment]
i change 'test' and 'logs' to '/test' and '/logs'.It works.But another error was throw out.

----------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    benchmark(args)
  File "F:\3D SIS\code\lib\model\trainval.py", line 71, in benchmark
    net_module = importlib.import_module("lib.nets.backbones")
  File "D:\Anaconda3\Anaconda3c\envs\python368\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\3D SIS\code\lib\nets\backbones.py", line 8, in <module>
    from lib.nets.network import Network
  File "F:\3D SIS\code\lib\nets\network.py", line 11, in <module>
    from lib.layer_utils.proposal_layer import proposal_layer
  File "F:\3D SIS\code\lib\layer_utils\proposal_layer.py", line 5, in <module>
    from lib.layer_utils.nms_wrapper import nms
  File "F:\3D SIS\code\lib\layer_utils\nms_wrapper.py", line 3, in <module>
    from lib.layer_utils.nms.pth_nms import cpu_nms
  File "F:\3D SIS\code\lib\layer_utils\nms\pth_nms.py", line 4, in <module>
    from ._ext import nms
  File "F:\3D SIS\code\lib\layer_utils\nms\_ext\nms\__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'lib.layer_utils.nms._ext.nms._nms'
------------------------------------------------------------------------------------------

I didn't find file named '_nms.oy' in F:\3D SIS\code\lib\layer_utils\nms\_ext\nms.
and see what in line3 of 'F:\3D SIS\code\lib\layer_utils\nms\_ext\nms\__init__.py'
code:"from ._nms import lib as _lib, ffi as _ffi",what does that mean ,course i didn't find file _nms

                                                                                                                                     Best wishes!

**Comment by Sekunde** [comment]
Generally if lib/layer_utils/nms/_ext/nms/_nms.so file is there, pytorch should find it.
you can rebuild the nms and 3d roi pooling layer that are written in CUDA.
see, lib/layer_utils/nms/build.py and lib/layer_utils/roi_pooling/build.py
