### ISSUE TITLE
Example.sh not working 

### ISSUE THREAD

**Issue by jorgegarcia197** [Sekunde/3D-SIS#12]
The example.sh code is not working with me 

I get these errors: 

in Vox2mesh: examples_results/test not found not found directory or file
and in evaluate map: examples_results/benchmark_results not found directory or file

Hope you can help me out. 
Thanks

**Comment by Sekunde** [comment]
there should be an error even before the vox2mesh, which cause that the example_results/test is not created. maybe can you share the screenshot of that?

**Comment by jorgegarcia197** [comment]
ERROR: 

Archive:  example_result/scannet_benchmark_checkpoint.zip
   creating: example_result/scannet_benchmark_checkpoint/
  inflating: example_result/scannet_benchmark_checkpoint/step_1205541.pkl  
  inflating: example_result/scannet_benchmark_checkpoint/step_1205541.pth  
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from lib.model.trainval import train
  File "/home/jorge/3D-SIS/lib/model/trainval.py", line 15, in <module>
    from lib.datasets.dataset import Dataset
  File "/home/jorge/3D-SIS/lib/datasets/dataset.py", line 12, in <module>
    import torchvision.transforms as transforms
  File "/home/jorge/project/local/lib/python2.7/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/jorge/project/local/lib/python2.7/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/home/jorge/project/local/lib/python2.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/jorge/project/local/lib/python2.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/jorge/project/local/lib/python2.7/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/jorge/project/local/lib/python2.7/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory


Traceback (most recent call last):
  File "tools/scannet_benchmark/evaluate_semantic_instance.py", line 405, in <module>
    main()
  File "tools/scannet_benchmark/evaluate_semantic_instance.py", line 389, in main
    pred_files = [f for f in os.listdir(opt.pred_path) if f.endswith('.txt') and f != 'semantic_instance_evaluation.txt']
OSError: [Errno 2] No such file or directory: 'example_result/benchmark_result'


What I am curious about is that the problem is the cuda libraries? Right now i'm on CUDA 10.1

**Comment by Sekunde** [comment]
From the error, it seems the problem of CUDA, i suggest to use python 3.6 and cuda 8.
