### ISSUE TITLE
inference on scannetv2 don't work

### ISSUE THREAD

**Issue by lapetite123** [Sekunde/3D-SIS#16]
when I run "python main.py --cfg ScanNet/rpn_class_mask_5 --mode test --step 805146 --gpu 0" it reported the following error:
starting test on whole scan....
0it [00:00, ?it/s]Traceback (most recent call last):
  File "main.py", line 81, in <module>
    test(args)
  File "/home/3d-sis/3D-SIS/lib/model/trainval.py", line 95, in test
    SolverWrapper.test(net, dataloader, logger)
  File "/home/3d-sis/3D-SIS/lib/model/trainval.py", line 789, in test
    for iter, blobs in enumerate(tqdm(data_loader)):
  File "/home/miniconda3/envs/3d-sis/lib/python3.6/site-packages/tqdm/_tqdm.py", line 999, in __iter__
    for obj in iterable:
  File "/home/miniconda3/envs/3d-sis/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "/home/miniconda3/envs/3d-sis/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 297, in __init__
    self._put_indices()
  File "/home/miniconda3/envs/3d-sis/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in _put_indices
    indices = next(self.sample_iter, None)
  File "/home/miniconda3/envs/3d-sis/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 138, in __iter__
    for idx in self.sampler:
  File "/home/miniconda3/envs/3d-sis/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 34, in __iter__
    return iter(range(len(self.data_source)))
  File "/home/3d-sis/3D-SIS/lib/datasets/dataset.py", line 43, in __len__
    return len(self.scenes)
AttributeError: 'Dataset' object has no attribute 'scenes'

by the way I can successfully run demo code

**Comment by Sekunde** [comment]
It seems there is a problem in data loader, basically, the dataset is not found;
can you print out in the following code lines, in which 'if' it goes in and what is the content of data_location
https://github.com/Sekunde/3D-SIS/blob/master/lib/datasets/dataset.py#L32-L37
