### ISSUE TITLE
inference on cpu

### ISSUE THREAD

**Issue by mcfrain** [Sekunde/3D-SIS#19]
![image](https://user-images.githubusercontent.com/42530317/70846378-b5f54f80-1e93-11ea-8cb5-266ff8c4b9d9.png)
according to the screenshot, can i do infer only with a cpu?(my local computer only has a old gpu, like gtx730...)

**Comment by Sekunde** [comment]
Yes, just set those variable to 0.

**Comment by santhu937** [comment]
@mcfrain  did get the inference code working on cpu

Mine generates the following error


Traceback (most recent call last):
  File "main.py", line 84, in <module>
    benchmark(args)
  File "/Users/santhosh/Documents/projects/3D-SIS/lib/model/trainval.py", line 68, in benchmark
    net_module = importlib.import_module("lib.nets.backbones")
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/santhosh/Documents/projects/3D-SIS/lib/nets/backbones.py", line 8, in <module>
    from lib.nets.network import Network
  File "/Users/santhosh/Documents/projects/3D-SIS/lib/nets/network.py", line 11, in <module>
    from lib.layer_utils.proposal_layer import proposal_layer
  File "/Users/santhosh/Documents/projects/3D-SIS/lib/layer_utils/proposal_layer.py", line 5, in <module>
    from lib.layer_utils.nms_wrapper import nms
  File "/Users/santhosh/Documents/projects/3D-SIS/lib/layer_utils/nms_wrapper.py", line 3, in <module>
    from lib.layer_utils.nms.pth_nms import cpu_nms
  File "/Users/santhosh/Documents/projects/3D-SIS/lib/layer_utils/nms/pth_nms.py", line 4, in <module>
    from ._ext import nms
  File "/Users/santhosh/Documents/projects/3D-SIS/lib/layer_utils/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: dlopen(/Users/santhosh/Documents/projects/3D-SIS/lib/layer_utils/nms/_ext/nms/_nms.so, 2): no suitable image found.  Did find:
	/Users/santhosh/Documents/projects/3D-SIS/lib/layer_utils/nms/_ext/nms/_nms.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/santhosh/Documents/projects/3D-SIS/lib/layer_utils/nms/_ext/nms/_nms.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

Could u please help

**Comment by mcfrain** [comment]
@santhu937 ,Sorry to reply to you after so long.
i finally run the 3d-sis inference only on a cpu with more steps: 
1. set the two variables to 0 as the author says.
 # __C.MAX_IMAGE = 400
__C.MAX_IMAGE = 0
# __C.MAX_VOLUME = 2000000
__C.MAX_VOLUME = 0
2. you also need a gpu and install cuda and so on, even you only infer on cpu.(without  a gpu, that dont work on my pc.)
3. follow the author's guide, recompile nms and roi_pooling.
4. you may need to adjuste version of tf and so on.
![image](https://user-images.githubusercontent.com/42530317/75518187-4a0a9800-5a3b-11ea-95a5-c80bf91413f4.png)
