### ISSUE TITLE
About NMS

### ISSUE THREAD

**Issue by sidoniepc** [Sekunde/3D-SIS#26]
when I was running example, I got:

Traceback (most recent call last):
  File "main.py", line 84, in <module>
    benchmark(args)
  File "/home/sidonie/3D-SIS-master/lib/model/trainval.py", line 68, in benchmark
    net_module = importlib.import_module("lib.nets.backbones")
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/sidonie/3D-SIS-master/lib/nets/backbones.py", line 8, in <module>
    from lib.nets.network import Network
  File "/home/sidonie/3D-SIS-master/lib/nets/network.py", line 11, in <module>
    from lib.layer_utils.proposal_layer import proposal_layer
  File "/home/sidonie/3D-SIS-master/lib/layer_utils/proposal_layer.py", line 5, in <module>
    from lib.layer_utils.nms_wrapper import nms
  File "/home/sidonie/3D-SIS-master/lib/layer_utils/nms_wrapper.py", line 3, in <module>
    from lib.layer_utils.nms.pth_nms import cpu_nms
  File "/home/sidonie/3D-SIS-master/lib/layer_utils/nms/pth_nms.py", line 4, in <module>
    from ._ext import nms
  File "/home/sidonie/3D-SIS-master/lib/layer_utils/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /home/sidonie/3D-SIS-master/lib/layer_utils/nms/_ext/nms/_nms.so: undefined symbol: state

**Comment by Sekunde** [comment]
have you tried building the NMS from lib/layer_utils/nms by running python build.py ?

**Comment by sidoniepc** [comment]
is this because I use python3.5?

**Comment by sidoniepc** [comment]
well the problem is solved after using python3.6.  I didn't use build.py successfully.
