### ISSUE TITLE
Can your code worked in windows?

### ISSUE THREAD

**Issue by ncy906302** [Sekunde/3D-SIS#28]
Thank you for this project! Can your code worked in windows?
I got error in run "python build.py ", 
i have already installed the all of requirements.txt.

this is error message:
C:\python\3D-SIS-master\3D-SIS-master\lib\layer_utils\roi_pooling\src\cuda\roi_pooling_kernel.cu.o : fatal error LNK1107: 檔案無效或損毀: 無法在 0x82A8 讀取
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\torch041\lib\distutils\_msvccompiler.py", line 519, in link
    self.spawn([self.linker] + ld_args)
  File "C:\ProgramData\Anaconda3\envs\torch041\lib\distutils\_msvccompiler.py", line 542, in spawn
    return super().spawn(cmd)
  File "C:\ProgramData\Anaconda3\envs\torch041\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\ProgramData\Anaconda3\envs\torch041\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\ProgramData\Anaconda3\envs\torch041\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\link.exe' failed with exit status 1107

**Comment by Sekunde** [comment]
we never tried to run the code in windows, it seems that the .cu.o is not compatible;
check out this to recomplie .cu.o file
https://github.com/Sekunde/3D-SIS/tree/master/lib/layer_utils/roi_pooling/src/cuda

**Comment by ncy906302** [comment]
Thank you for your quick reply. i will try it on linux.
